/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kbot_mxnet_MXNetwork */

#ifndef _Included_kbot_mxnet_MXNetwork
#define _Included_kbot_mxnet_MXNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kbot_mxnet_MXNetwork_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    kbot_mxnet_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kbot_mxnet_MXNetwork_kbot_1mxnet_1version
  (JNIEnv *, jclass);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    mxnet_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kbot_mxnet_MXNetwork_mxnet_1version
  (JNIEnv *, jclass);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    constructNet
 * Signature: (I[ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[FII)J
 */
JNIEXPORT jlong JNICALL Java_kbot_mxnet_MXNetwork_constructNet
  (JNIEnv *, jobject, jint, jintArray, jstring, jstring, jstring, jobjectArray, jfloatArray, jint, jint);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    constructNetLoad
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_kbot_mxnet_MXNetwork_constructNetLoad
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    disposeNet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kbot_mxnet_MXNetwork_disposeNet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    cloneNet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kbot_mxnet_MXNetwork_cloneNet
  (JNIEnv *, jobject);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    save
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kbot_mxnet_MXNetwork_save
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    predict1D_m
 * Signature: ([[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_kbot_mxnet_MXNetwork_predict1D_1m
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    predict1D
 * Signature: ([F)F
 */
JNIEXPORT jfloat JNICALL Java_kbot_mxnet_MXNetwork_predict1D
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    fit1D
 * Signature: ([[F[F)V
 */
JNIEXPORT void JNICALL Java_kbot_mxnet_MXNetwork_fit1D
  (JNIEnv *, jobject, jobjectArray, jfloatArray);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    fit1D_mb
 * Signature: ([[F[FI)V
 */
JNIEXPORT void JNICALL Java_kbot_mxnet_MXNetwork_fit1D_1mb
  (JNIEnv *, jobject, jobjectArray, jfloatArray, jint);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    predict2D_m
 * Signature: ([[F)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_kbot_mxnet_MXNetwork_predict2D_1m
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    predict2D
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_kbot_mxnet_MXNetwork_predict2D
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    fit2D
 * Signature: ([[F[[F)V
 */
JNIEXPORT void JNICALL Java_kbot_mxnet_MXNetwork_fit2D
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     kbot_mxnet_MXNetwork
 * Method:    fit2D_mb
 * Signature: ([[F[[FI)V
 */
JNIEXPORT void JNICALL Java_kbot_mxnet_MXNetwork_fit2D_1mb
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
